Vagrant.configure("2") do |config|
 config.vm.provider "virtualbox" do |vb|
   vb.customize ["modifyvm", :id, "--memory", "1024"]
 end
 config.vm.box = "centos/7"
 config.vm.hostname = "rancher-hst"
 config.vm.network "private_network", ip: "192.168.50.60"
 config.vm.provision :shell, path: "../host.sh"
end
